mmastrac/rust-ctor

ctor/src/lib.rs

We can parse directly as syn::ItemFn rather than parsing as syn::Item followed by `if let`.

Parse as ItemFn

---

ctor/src/lib.rs
tests/src/dylib_load.rs

this patch is adding FreeBSD support to `ctor`
`cargo test` is successful.
I've tested it via the crate `typetag` and it seems working, however some code review and more hint on how to improve tests could be helpful
as soon as I can, I'll add CI support for FreeBSD

Add initial support to FreeBSD

---

ctor/src/lib.rs

Experimentation with [Crabapple](https://github.com/Crabapple-iOS/iOSRustTweak) has confirmed that `link_section = "__DATA,__mod_init_func"` works for iOS targets.

Adds iOS support

---

ctor/src/lib.rs

Makes the macro place a compile_error in the output on unsupported platforms, which causes a nice error, pointing to the exact location of the problem:
```
error: #[dtor] is not supported on the current target
--> ctor\src/example.rs:29:1
|
29 | #[dtor]
| ^^^^^^^
|
= note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
Closes #11

Make unsupported targets hard error

---

ctor/src/lib.rs

Also makes it so that the original function is preserved in the output, including visibility. In theory, ctor functions can be called just fine during normal execution as long as the user makes them able to handle that.
Closes #96

Make all generated function extern "C"

---

test.sh

Just punting on `+crt-static` builds. We cannot build cdylib in `+crt-static` for the same reasons we cannot build them in the `musl` target.
```
error: cannot produce cdylib for ... as the target `x86_64-unknown-linux-gnu` does not support these crate types
```
For googlers that are stumbling across this error, `+crt-static` won't let you create `cdylib` files.

If building w/+crt-static, set explicit target

---

README.md
ctor/src/lib.rs
tests/src/dylib_load.rs

I don't know how to extensively test this, but things like value-bag and log 0.4.14 now compile on OpenBSD with this. (and the programs using them do not immediately explode)
I encountered the need for this today when trying to build a project who uses `async-std`, who eventually (via `async-io`) pulls in the `log` crate who switched to using `value-bag`, which then uses this crate.
Let me know what I can do to improve this further if needed. Thank you!

Copycat attempt to support OpenBSD, based on #116.

---

ctor/src/lib.rs
tests/src/dylib_load.rs

This adds support for [illumos](https://illumos.org) systems.  The tests appear to pass:
```
$ uname -a
SunOS newcastle 5.11 rti-master-0-gf6ef42236c i86pc i386 i86pc
$ cargo test
Finished test [unoptimized + debuginfo] target(s) in 0.02s
Running target/debug/deps/ctor-96ead4d202c4bf8d
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running target/debug/deps/tests-a7da501531d30b78
running 2 tests
test test::test_initialized ... ok
test test::test_dylib ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.02s
We don't test shutdown, but if you see this message it worked!
Doc-tests tests
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished …
```

add support for illumos

---

ctor/src/lib.rs

The code for ctors on statics already uses the `#[doc(hidden)]` attribute to suppress symbols created by ctor out of rustdoc output, but the one for functions does not.
If you add that annotation to the function wrapped by `ctor`, it'll suppress the function at global scope, but not the static that ctor generates.
This patch adds `#[doc(hdiden)]` to the latter as well.
---
Test Plan:
EDIT: I couldn't find any contributing guidelines or anything, so if you want me to do more to test this than I have, just let me know.
Tests pass before and after this patch.
Examples before/after of rustdoc output from one of my crates:
Before this patch is applied, the following statics appear in rustdoc:
After this patch is applied, nothing from ctor appears in rustdoc:

Suppress `ctor_ident` in docs (Function)

---

ctor/Cargo.toml
ctor/src/example.rs
ctor/src/lib.rs
tests/Cargo.toml
tests/src/dylib.rs
tests/src/dylib_load.rs
tests/src/lib.rs

Add a feature `used_linker` that uses `#[used(linker)]`, an unstable `+nightly` feature that might fix some of the ctor pain.
This may fix #280, #206 and related bugs.

Add used_linker feature

---

ctor/src/lib.rs

This probably doesn't change much, but the `__cxa_atexit` function takes one `(void *)` parameter, see [LSB](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib---cxa-atexit.html) or 
`cxa_atexit_callback` in the [darwin-crt](https://opensource.apple.com/source/gcc/gcc-5659/gcc/config/darwin-crt3.c.auto.html):
```c
typedef void (*cxa_atexit_callback)(void *);
```

Use correct __cxa_atexit function definition

---

ctor/src/lib.rs

On `master`, the following test succeeds to mutate and read the mutable static `test` boolean without the use of an `unsafe` keyword:
```rust
extern crate ctor;
use ctor::*;
static mut test: bool = false;
#[ctor]
static STATIC_CTOR: bool = {
test = true;
test
}
```
This PR fixes the issue

Move static ctor out of unsafe context

---

ctor/src/lib.rs

This PR adds `#[allow(non_snake_case)]` to the emitted constructor identifier to prevent `#[warn(non_snake_case)]` from complaining in some situations.
The suffix used when generating the constructor identifier already triggers this warning, so regardless of the input identifier the generated identifier is already in violation of this lint:
```
λ cargo test
Compiling ctor v0.2.5 (/Users/maxdeviant/projects/rust-ctor/ctor)
warning: function `foo___rust_ctor___ctor` should have a snake case name
--> ctor/src/example.rs:10:4
|
10 | fn foo___rust_ctor___ctor() {}
|    ^^^^^^^^^^^^^^^^^^^^^^ help: convert the identifier to snake case: `foo_rust_ctor_ctor`
|
= note: `#[warn(non_snake_case)]` on by default
warning: `ctor` (example "example") generated 1 warning
```

Emit `#[allow(non_snake_case)]` for constructor identifier

---

ctor/src/lib.rs

In my project, I have a module named `core`, it clashes with the Rust core within the `ctor` macro, as you can see from the error:
```shell
$ ls -l src
Permissions Links Size User  Group Date Modified Name
.rw-r--r--      1    0 steve steve  8 Dec 19:57  core.rs
.rw-r--r--      1   79 steve steve  8 Dec 19:57  main.rs
$ cat src/main.rs
mod core;
use ctor::ctor;
#[ctor]
static INT: i32 = {
1
};
fn main() {}
$ cargo b -q
error[E0433]: failed to resolve: could not find `marker` in `core`
--> src/main.rs:5:1
|
5 | #[ctor]
| ^^^^^^^ could not find `marker` in `core`
|
= note: this error originates in the attribute macro `ctor` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
|
3 + use core::marker;
|
3 + use std::marker;
|
error[E0433]: …
```

refactor: use ::core instead of core

---

Cargo.lock
ctor/src/lib.rs
tests/src/dylib_load.rs

- Added tvOS cfg flags for tvOS support
How was this tested (WIP):
- cargo +nightly build -Z build-std=std --workspace --target aarch64-apple-tvos
- cargo +nightly build -Z build-std=std --workspace --target aarch64-apple-tvos-sim
- cargo +nightly build -Z build-std=std --workspace --target x86_64-apple-tvos
- cargo +nightly build -Z build-std=std --workspace --target aarch64-apple-ios
- cargo +nightly build -Z build-std=std --workspace --target aarch64-apple-ios-sim

Added tvOS support 

---

ctor/src/lib.rs

The code is correct by putting it actually in `__DATA`; update the docs to match that.
The assembler only sets the `S_MOD_INIT_FUNC_POINTERS` section flag if the `__DATA` segment is used, and without that, dyld will just ignore it. It's the linker's job to move it to `__DATA_CONST` when targetting a new enough OS version.

Mention correct `link_section` in docs for Apple

---

.gitignore
Cargo.lock
Cargo.toml
README.md
codegen/src/macros.rs
codegen/src/main.rs
ctor/src/gen.rs
tests-wasm/Cargo.toml
tests-wasm/src/lib.rs

Add support for wasm targets. Note that only one wasm start target is allowed (aka, one and only one #[ctor] will be allowed).
Fixes #273

WASM support

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
codegen/Cargo.toml
codegen/src/macros.rs
codegen/src/main.rs
ctor/src/example.rs
ctor/src/gen.rs
ctor/src/lib.rs
rust-toolchain.toml
tests-edition-2018/Cargo.toml
tests-edition-2018/src/main.rs
tests-edition-2021/Cargo.toml
tests-edition-2021/src/main.rs
tests-edition-2024/Cargo.toml
tests-edition-2024/src/main.rs
tests-wasm/src/lib.rs
tests/Cargo.toml
tests/src/dylib.rs
tests/src/dylib_load.rs
tests/src/lib.rs

Rust 2024 is coming and requires some minor lint fixes.
There's some strangeness in how clippy and Rust process unsafe attributes. We use a trick to determine the current edition and generate either 2021 or 2024 compatible output.

Be as warning-safe as we can with Rust 2024 around the corner

---

Cargo.lock
ctor-proc-macro/Cargo.toml
ctor-proc-macro/src/lib.rs
ctor/Cargo.toml
ctor/src/lib.rs
dtor/src/lib.rs
shared/src/macros/mod.rs

The recent refactoring in 0.3.x to split ctor into a declarative/proc_macro hybrid crate broke some downstream uses of ctor where ctor-annotated items were injected into code that was not importing the ctor crate.
Fixes #325 (a breakage in `napi-rs` reported by @Brooooooklyn by offering two options for re-export of ctor items:
1) #[ctor] now has a `crate_path` attribute allowing re-exporters to specify a private re-export path:
```rust
#[ctor(crate_path=::my_crate::private::ctor)]
unsafe fn foo() {
}
```
2) A new `declarative` module that avoids any `proc_macro` usage is available. This module exposes a macro that parses #[ctor]-annotated items. As this declarative macro is fully-implemented with `macro_rules!` and `$crate`-relative references to support macros, there should be no issues …

Allow easier re-export of ctor crate

---

shared/src/macros/mod.rs
shared/tests/expand-darwin/ctor_doc.expanded.rs
shared/tests/expand-darwin/ctor_doc.rs
shared/tests/expand-darwin/ctor_static.expanded.rs
shared/tests/expand-darwin/ctor_static.rs
shared/tests/expand-darwin/dtor_doc.expanded.rs
shared/tests/expand-darwin/dtor_doc.rs
tests/system/Cargo.toml
tests/system/src/dylib.rs

Fix for doc comments not allowed before `#[ctor]` using declarative macro (fixes issue mentioned in #332).
Allow this:
```rust
/// Doc 1
#[ctor]
/// Doc 2
unsafe fn foo() { }
```

Allow arbitrary #[meta] before and after #[ctor]/#[dtor]

---

Cargo.toml
ctor/src/example.rs
ctor/src/lib.rs
dtor/src/lib.rs
shared/src/macros/mod.rs
shared/tests/errors/ctor_anon.rs
shared/tests/errors/ctor_anon.stderr
shared/tests/expand-darwin/ctor.expanded.rs
shared/tests/expand-darwin/ctor_anon.expanded.rs
shared/tests/expand-darwin/ctor_anon.rs
shared/tests/expand-darwin/ctor_attribute.expanded.rs
shared/tests/expand-darwin/ctor_doc.expanded.rs
shared/tests/expand-darwin/ctor_mutli_attr.expanded.rs
shared/tests/expand-darwin/ctor_unsafe.expanded.rs
shared/tests/expand-darwin/ctor_used_linker_attr.expanded.rs
shared/tests/expand-darwin/ctor_warn.expanded.rs
shared/tests/expand-darwin/dtor.expanded.rs
shared/tests/expand-darwin/dtor_anon.expanded.rs
shared/tests/expand-darwin/dtor_anon.rs
shared/tests/expand-darwin/dtor_doc.expanded.rs
tests/edition-2024/Cargo.toml
tests/system/src/lib.rs

Fully fixes #332 by offering two methods of generating anonymous constructors:
```rust
#[ctor(anonymous)]
unsafe fn foo() { }
/// Allowed because this ctor is anonymous
#[ctor(anonymous)]
unsafe fn foo() { }
```
or
```rust
const _: () = { 
#[ctor]
unsafe fn foo() { }
}
const _: () = { 
#[ctor]
unsafe fn foo() { }
}
```

Allow anonymous ctor (either explicit or via anonymous)

---

.github/workflows/rust.yml
Cargo.lock
shared/src/macros/mod.rs
tests/wasm/Cargo.toml
tests/wasm/src/lib.rs

closes: https://github.com/mmastrac/rust-ctor/issues/336
You can test with: 
```rs
use ctor::ctor;
#[ctor]
pub fn init() {
println!("Hello");
}
#[unsafe(no_mangle)]
pub extern "C" fn _start() {
println!("Start");
}
```
```sh
cargo build --target wasm32-wasip1
wasmer run target/wasm32-wasip1/debug/xxx.wasm
```
But according to [inventory](https://github.com/dtolnay/inventory/blob/5e915d4d197432b73375ad21e08a1ee8275d8309/src/lib.rs#L543), `.init_array` only support wasm after rust 1.85 stable. We should check this and provide a fallback strategy(`wasm_bindgen` or panic).
Any suggestion?

Support wasm without wasm_bindgen

---

README.md

README.md: mismatched closing delimiter

---

README.md
ctor/src/lib.rs
shared/src/macros/mod.rs
shared/tests/expand-darwin/ctor.expanded.rs
shared/tests/expand-darwin/ctor_anon.expanded.rs
shared/tests/expand-darwin/ctor_doc.expanded.rs
shared/tests/expand-darwin/ctor_static.expanded.rs
shared/tests/expand-darwin/ctor_unsafe.expanded.rs
shared/tests/expand-darwin/ctor_used_linker_attr.expanded.rs
shared/tests/expand-darwin/ctor_warn.expanded.rs
shared/tests/expand-darwin/dtor.expanded.rs
shared/tests/expand-darwin/dtor_anon.expanded.rs
shared/tests/expand-darwin/dtor_doc.expanded.rs

`ctor` fails to run on cranelift partially because it is missing an explicit link section flag: https://github.com/rust-lang/rustc_codegen_cranelift/issues/1588#issuecomment-3047959818
The fully-correct link section should be `__DATA,__mod_init_func,mod_init_funcs`
Partial fix for #339

Add macOS `mod_init_funcs` flag
